name: CI

on: push

jobs:
  linting:
    name: GitHub Action for pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: GitHub Action for pylint
        uses: zerodaysec/github-action-for-python@v0.1.0
        with:
          args: pipenv install && pipenv run pylint **/*.py

